### ISSUE TITLE
python code has no encoding

### ISSUE THREAD

**Issue by Mielai1l** [DavidJacobson/SafeText#5]
When running the code I got: "no encoding declared; see http://python.org/dev/peps/pep-0263/ for details".
I changed the code and this made it work (with python 3):
git diff
`diff --git a/characters_safetext.py b/characters_safetext.py
index 8b4df1d..7493970 100644
--- a/characters_safetext.py
+++ b/characters_safetext.py
@@ -1,3 +1,7 @@
+#! /usr/bin/env python3
+# -*- coding: utf-8 -*-
+# çedille
+
 \# This is a file to store all the characters that SafeText will look out for
 
 \# Zero width characters are visible when reading, as they take up no space. However, they can be used in fingerprinting.
diff --git a/safetext.py b/safetext.py
index e578f39..9c06efc 100644
--- a/safetext.py
+++ b/safetext.py
@@ -1,3 +1,6 @@
+#! /usr/bin/env python3
+# -*- coding: utf-8 -*-
+# çedille
 \# SafeText
 \# This script takes an input of a text file, and removes any characters that could be unique identifiers that would
 \# reveal an otherwise confidential source.
`

**Comment by DavidJacobson** [comment]
Didn't realize this was an issue, thanks. Fixed!
